/*
 * Copyright (c) 1990 The Regents of the University of California.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that: (1) source distributions retain this entire copyright
 * notice and comment, and (2) distributions including binaries display
 * the following acknowledgement:  ``This product includes software
 * developed by the Computer Systems Laboratory, University of
 * California, Santa Barbara and its contributors'' in the documentation
 * or other materials provided with the distribution and in all
 * advertising materials mentioning features or use of this software.
 *
 * Neither the name of the University nor the names of its contributors
 * may be used to endorse or promote products derived from this software
 * without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

/* LINTLIBRARY */

#include "ipw.h"

#include "_error.h"

/* 
** NAME
**         usrerr, uferr, syserr -- deferred error handling
**  
** 
** SYNOPSIS
**         void usrerr(format, ...)
**         char *format;
** 
**         void uferr(fd)
**         int fd;
** 
**         void syserr()
**  
** 
** DESCRIPTION
**         These functions save error information in global variables,
**         for later incorporation in error messages generated by the
**         error or warn functions.
** 
**         usrerr saves the error message described by the printf-style
**         {format} and optional additional arguments.
** 
**         uferr saves the file descriptor {fd}, which may be used by
**         error or warn to obtain the associated file name.
** 
**         syserr causes any current UNIX system error condition to be
**         saved.  The associated error message will be incorporated in
**         the output generated by error or warn.
**  
** 
** GLOBALS ACCESSED
**         _usrerr         usrerr stores its error message in this
**                         string.
** 
**         _fderr          uferr sets this to {fd}.
** 
**         _erno          syserr sets this to the current UNIX "errno"
**                         value.
**  
** 
** APPLICATION USAGE
**         usrerr is called to save topical information that would
**         otherwise be passed directly to error or warn; for example,
**         if error or warn may not be called until the current
**         function returns.
** 
**         uferr should be called before error or warn if the name of
**         the file accessed by {fd} should appear in the error
**         message.  Note that any IPW library functions that deal with
**         file descriptors will call uferr themselves whenever
**         appropriate.
** 
**         syserr is seldom invoked by application programs, since they
**         do not directly invoke UNIX system calls.
**  
** 
** SEE ALSO
**         IPW: error, uropen
** 
**         UNIX: errno, perror, vsprintf
*/  

void
uferr(fd)
	int             fd;		/* file descriptor		 */
{
	_fderr = fd;
}

#ifndef	lint
static char     rcsid[] = "$Header: /nfs/home/share1/ipw-1.1/ipw-1.1/src/lib/libipw/error/RCS/uferr.c,v 1.6 1997/04/09 02:42:40 ceretha Exp $";

#endif
